export const sectors = {
  0: 'Sol',
  1: 'Altus',
  2: 'Barnard',
  3: 'Cancri',
  4: 'Gothmar',
  5: 'Cantolus',
  6: 'Idun',
  7: 'Kelvin',
  8: '',
  9: '',
  10: '',
  11: '',
  12: '',
  13: 'Rictus',
  14: '',
  18: 'Marspira',
  19: 'Talus',
  20: 'Umlaut',
  21: 'Draco',
  31: 'Xzar',
  33: 'Severin',
  38: 'Mirin',
  48: 'Trigon',
  53: "L'estrade",
};
// NOTE: some sector names and numbers are mismatched/shared. eg. azur secundus is in sector 20 which in-game is sten but also something else
